name: coffeestore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0
  scoped_model: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assests/img/tomato.jpg
    - assests/img/raspberry-smoothie.jpg
    - assests/img/plum.jpg
    - assests/img/pink-grape.jpg
    - assests/img/lime.jpg
    - assests/img/mint-tea.jpg
    - assests/img/apple-smoothie.jpg
    - assests/img/black-coffee.jpg
    - assests/img/black-smoothie.jpg
    - assests/img/black-tea.jpg
    - assests/img/brown-tea.jpg
    - assests/img/cappuccino.jpg
    - assests/img/english-tea.jpg
    - assests/img/espresso.jpg
    - assests/img/herbal-tea.jpg
    - assests/img/kiwi-smoothie.jpg
    - assests/img/latte.jpg
    - assests/img/lemon.jpg
